### ISSUE TITLE
Ability to define containers in YAML without automatically starting them

### ISSUE THREAD

**Issue by iangkent** [signalfuse/maestro-ng#108]
It would be nice to be able to define a container instance in yaml file but not run it by default.
Similar to the way 'docker create' works.
See https://docs.docker.com/reference/commandline/cli/#create

We have some containers that host debug, monitoring tools that we don't want to run by default.
We want to be able to create containers but not run until needed.

**Comment by mpetazzoni** [comment]
Pushing back to 0.2.6.

**Comment by kkebb** [comment]
Hello, I've tried used the omit: true option for one of the services, however, it's still starting up the unnamed service (i.e. meastro start) .. I am using the latest maestro version. Any help would be appreciated.

**Comment by mpetazzoni** [comment]
Re-opening for investigation

**Comment by mpetazzoni** [comment]
@kkebb I'm not able to reproduce the problem. Where did you set `omit: true` in your YAML?
