### ISSUE TITLE
image pulling broken with docker-py 0.7.0

### ISSUE THREAD

**Issue by cmheisel** [signalfuse/maestro-ng#109]
I've got two virtualenvs, one that I created last week, and another created this week. Both have the current version of maestro-ng installed, but the one from this week won't pull images.

When I pull images from a private repository in quay.io with this week's virtualenv I get a success message during maestro pull but I get this traceback when I run maestro start $my_service
Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/maestro/__main__.py", line 207, in main
        getattr(c, options.command)(**vars(options))
      File "/usr/local/lib/python2.7/dist-packages/maestro/maestro.py", line 299, in start
        ignore_dependencies, concurrency, reuse))
      File "/usr/local/lib/python2.7/dist-packages/maestro/maestro.py", line 229, in _audit_play
        raise e
APIError: 404 Client Error: Not Found ("No such image: quay.io/{{ my org }}/{{ my repo }}:{{ my_tag}} (tag: {{ my_tag }})")

I SSH'd onto my docker ships and confirmed that they work if I manually docker login with the same creds I'm feeding maestro, and I can docker pull the image.

Then I tried the same command with the virtualenv from last week and IT WORKED.

Near as I can tell the difference is that docker-py in the functional virtualenv is 0.6.0 and the version in the broken virtualenv is 0.7.0

When I uninstalled 0.7.0 and pip install docker-py==0.6.0 in the broken install it started working.

**Comment by mpetazzoni** [comment]
I haven't been able to reproduce the problem with `docker-py` 0.7.1. Is this still an issue if you upgrade?

**Comment by cmheisel** [comment]
Yup I had the issue this morning with a fresh install of maestro-ng 0.2.4.1, and docker-py 0.7.1.

It was able to pull public images in without a problem, but it failed on a private image on quay.io.

When I ran the same maestro.yaml through maestro-ng 0.2.4.1 and docker-py 0.6.0 it worked like a charm

**Comment by mpetazzoni** [comment]
Can you post here what you see in the Docker daemon's log while you do the pull? If you can too, could you capture the HTTP requests made by Maestro and look for the `X-Registry-Auth` header in the request?

Thanks!

**Comment by mpetazzoni** [comment]
Ok, found the problem. It was a bug in `docker-py` (in the way it maps the resolved registry URL with the known auth data). At the same time, someone else also found it and send a pull request with the fix to `docker-py`, which I merged promptly.

Feel free to upgrade your `docker-py` install if you can:

```
$ pip install --upgrade git+https://github.com/docker/docker-py.git
```

https://github.com/docker/docker-py/commit/1fb887c268883574bc807423b00192008e195710
