### ISSUE TITLE
Ability to declare a container volume only (no host binding)

### ISSUE THREAD

**Issue by xilon-jul** [signalfuse/maestro-ng#114]
There is no support for container volume only. We are compelled to declare a binding on the host which is not what we always want. Docker provides container only volumes (no host mapping) in the form -v /container/volume/path.  Maestro should support this also.

**Comment by xilon-jul** [comment]
Such a code would do the trick (docker.py version 0.7.1) : 

from docker import Client
import time

docker = Client(base_url='unix://var/run/docker.sock')
response1 = docker.create_container('debian:wheezy', detach=True, volumes=['/new'],
    command="/bin/bash", name='mycontainer2')
docker.start(response1['Id'])
time.sleep(1)
response = docker.create_container('debian:wheezy',
    command="/bin/bash",stdin_open=True)
docker.start(response['Id'], volumes_from='mycontainer2')
time.sleep(1)
print(docker.logs(response['Id']))
~

**Comment by xilon-jul** [comment]
Please check PR : https://github.com/signalfuse/maestro-ng/pull/115. It aims at providing a new schema version 3 that understands volumes with no host binding. Any feedback would be greatly appreciated. Thanks

**Comment by mpetazzoni** [comment]
I'd really like to not change the direction of volume mappings again, unless I hear from more people that they are OK with it. I'm open to suggestions on how to declare container-only volumes in the YAML in a sensible way.

**Comment by xilon-jul** [comment]
Maxime, do we open another issue or work on this one and make a new proposal for this feature ?

**Comment by xilon-jul** [comment]
I see that you plan this issue for 0.2.5, it would be great to merge the work for volumes_from also. Lolski has a fork containing the modification, we should check with him it we could make a PR of his forkk for the 0.2.5 milestone (see https://github.com/lolski/maestro-ng)

**Comment by xilon-jul** [comment]
@mpetazzoni  To declare volume with no binding I propose to have a new key named "container_volumes" under the "instances" section. This key should accept a list of values representing the volume path inside the container ?

**Comment by xilon-jul** [comment]
I've made another PR https://github.com/signalfuse/maestro-ng/pull/116. This one implements both features (volumes_from and container_volumes)
