### ISSUE TITLE
Arbitrary options passed through to docker run

### ISSUE THREAD

**Issue by bradjones1** [signalfuse/maestro-ng#125]
While there are some common options configurable through the YAML file, is there an option to pass through more esoteric options like --cap-add? Perhaps even just an option to provide them as a string, e.g., "run_options"?

**Comment by mpetazzoni** [comment]
Arbitrary options to the container start can't be supported by Maestro. Maestro relies on `docker-py`, so only the functionality exposed by it can be used by Maestro. I'm certainly missing a few things from `docker-py`, as their addition in Maestro is mostly usage-driven. If you need something specific, and it's supported by `docker-py`, feel free to send the corresponding pull request (or feature request)!

**Comment by bradjones1** [comment]
I believe composer also uses docker-py and they've included support for this? Looks pretty straightforward? See: https://github.com/docker/compose/commit/9a04ae0ddf585dc986214c458510c0c8a999553c

**Comment by mpetazzoni** [comment]
It is, for options that `docker-py` supports. `cap_add` is one of them. My comment was about supporting _arbitrary_ options.

**Comment by bradjones1** [comment]
Would I need to submit a pull request to add cap_add to maestro-ng? I'm not a python guy but I think I could find my way if it's not natively supported by virtue of using docker-py.
