### ISSUE TITLE
get InsecurePlatformWarning from urllib3 when pulling image

### ISSUE THREAD

**Issue by iangkent** [signalfuse/maestro-ng#126]
I am running latest maestro-ng (git+git://github.com/signalfuse/maestro-ng) using python 2.7.5.

When run maestro pull command I get the following error:

/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by mpetazzoni** [comment]
This is a known issue and it takes root in a bug in Python versions prior to 2.7.9. If you upgrade to 2.7.9, the message will go away.
