### ISSUE TITLE
Updating hosts file in linked/dependent containers on restart

### ISSUE THREAD

**Issue by bradjones1** [signalfuse/maestro-ng#130]
Similar to the line of discussion on https://github.com/docker/docker/issues/6350 I'm wondering if it's possible to have the hosts files inside surviving (non-restarted) containers get updated with the new IP of the restarted container? As it stands right now it appears I have to manually go through and restart containers when those they're linked to get restarted, so as not to break communication?

**Comment by ykushch** [comment]
Yep, I think it could be a feature that could be activated by flag or so.

**Comment by bradjones1** [comment]
https://github.com/signalfuse/maestro-ng/issues/154 seems like a more elegant solution. Closing.
