### ISSUE TITLE
memory limit has no effect

### ISSUE THREAD

**Issue by sam0737** [signalfuse/maestro-ng#135]
Setting memory limit has no effect (as confirmed with `docker stats`), but if I run the container manually `docker run` everything is good (so it's not my system/kernel/cgroup problem).

I am suspecting it's related to this: https://github.com/docker/docker-py/issues/623

docker server: 1.6.2
docker client: 1.6.2
docker-py 1.2.3
maestro-ng: 0.2.6.2
on Ubuntu 14.04 LTS

**Comment by mpetazzoni** [comment]
Thanks. This looks like a `docker-py` issue indeed. As soon as the problem is resolved there, I'll see if I need to change something in MaestroNG.
