### ISSUE TITLE
docker-py client version is too old

### ISSUE THREAD

**Issue by kuhess** [signalfuse/maestro-ng#142]
Hi,

I upgraded my Docker server to 1.7.1. But `maestro` crashed with this error:
```
APIError: 400 Client Error: Bad Request ("client is too old, minimum supported API version is 1.12, please upgrade your client to a newer version")
```

Maybe I miss something, but why don't use automatic resolution instead of static version?
I propose [this PR](https://github.com/signalfuse/maestro-ng/pull/141) to fix it.

**Comment by mpetazzoni** [comment]
Fix is merged in; `api_version` parameter now available to address this. Default Docker version is now also 1.15 since July, which will be released soon with 0.2.7.

**Comment by kamaljeetrathi** [comment]
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
I am using DockerClientConfig config = DockerClientConfig.createDefaultConfigBuilder().withVersion("1.8.2").build;

it is giving me an error :client is too old, minimum supported API version is 1.12, please upgrade your client to a newer version

**Comment by mpetazzoni** [comment]
@kamaljeetrathi What version of MaestroNG are you using?

```
pip freeze | grep maestro
```

**Comment by kamaljeetrathi** [comment]
@mpetazzoni  I am new to docker and doesnt know about MaestroNG nor I have installed it,nor the above command is giving me any output. I am using 
DockerClientConfig.createDefaultConfigBuilder().withVersion("1.8.2").build; line of code in java and installed docker and added maven dependency 
<dependency>
      <groupId>com.github.docker-java</groupId>
      <artifactId>docker-java</artifactId>
      <version>2.1.1</version>
</dependency>
and running it.

**Comment by mpetazzoni** [comment]
If it's not a MaestroNG-related issue I can't really help you here. But it just seems like your `docker-java` library is too old. Make sure you use this one: https://github.com/docker-java/docker-java which is up-to-date and should work with recent versions of Docker.

**Comment by kamaljeetrathi** [comment]
@mpetazzoni thanks Now I am doing it with rest api: https://docs.docker.com/reference/api/docker_remote_api_v1.20/.
just wanted ask about the client and server authethication.How will i authenticate my client if my server is on another machine.
For now my client and server both are on local machine.

**Comment by mpetazzoni** [comment]
There is no user/password authentification to talk to a Docker daemon. You can have TLS-based security with client certificates if you want. Those are questions for the Docker community though, not Maestro.

**Comment by kamaljeetrathi** [comment]
Hi
How we can connect docker container to dhcp.

Regards,
*Kamaljeet Rathi*
Infiverve Technologies Pvt Ltd.
Mobile: +91 9762054095 | http://www.infiverve.com
