### ISSUE TITLE
Add support for log_config (log-driver and log-opt)

### ISSUE THREAD

**Issue by jverhoeven** [signalfuse/maestro-ng#143]
This feature exists since docker 1.6 and looks like finally fixes the long lasting logging issue (like not being able to rotate on the host), especially with the addition of syslog tags and fluentd driver in 1.8.

I was going to make a PR for it but found out it requires the use of host_config in docker-py which requires some refactoring in the Maestro code. Providing host config options in start seems to be marked deprecated. I noticed the API has gone up to 1.15 so using host_config in the create_container should no longer be an issue.

Hope you can find some time to add this feature to your great orchestration tool.

**Comment by jverhoeven** [comment]
Did make a PR anyway: https://github.com/signalfuse/maestro-ng/pull/144

**Comment by mpetazzoni** [comment]
This has been merged in #144.
