### ISSUE TITLE
Add support for volumes-from

### ISSUE THREAD

**Issue by jsierles** [signalfuse/maestro-ng#49]
From Docker 0.11, volumes from allows mounting volumes from other containers. Use case: sshd container to connect to and update an app container's git repo.

current docker-py supports this so should be a simple addition. I'll try to get to it if nobody does.

**Comment by xilon-jul** [comment]
@lolski thanx, any idea when this feature would get merged in the official repo ?

**Comment by mpetazzoni** [comment]
Forgot to mention that this was implemented in 0.2.5 (see #114).
