### ISSUE TITLE
Maestro pull fails with "DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled."

### ISSUE THREAD

**Issue by corradio** [signalfuse/maestro-ng#76]
Docker-client's last update requires HTTPS by default on private registries:
https://github.com/docker/docker-py/blob/7a462970852a2578c3869e581a57dd70eaa22217/ChangeLog.md

We should have a global flag that enables pulls from unsecure registries.

L346 needs to be changed with an added `insecure_registry=True` parameter
https://github.com/signalfuse/maestro-ng/blob/fe89532acb3a61e84294de9d418e69b6fae04467/maestro/plays/tasks.py#L346

**Comment by MohamedBassem** [comment]
Hello, any updates in this issue ?

**Comment by EronWright** [comment]
Testing this, I still see the issue when using literal FQINs (fully-qualified image names) in the service section.  Please have a look.

**Comment by mpetazzoni** [comment]
@EronWright Thanks. Could you give an example snippet of your YAML? What does your FQIN look like?

**Comment by brk3** [comment]
I believe the issue still occurs when you don't specify a registries section at all (i.e. no auth data is needed).

The following YAML breaks it for me:

    __maestro:                                                                                             
      schema: 2                                                                                            

    name: demo                                                                                             

    ships:                                                                                              
      vm1: {ip: 10.10.10.3}                                                                             
      vm2: {ip: 10.10.10.4}                                                                             

    services:                                                                                           
      rabbitmq:                                                                                         
        image: <local-insecure-registry-ip>:5000/rabbitmq                                                             
        instances:                                                                                      
          rabbit1:                                                                                      
            ship: vm1                                                                                   
            ports: &rabbit_ports {rabbitmq_public: 5672, rabbitmq_epmd: 4369, rabbitmq_node: 25672,        
                                  rabbitmq_management: 15672}                                           

Would you consider allowing registries to be defined without auth data?  (I can do up a patch if needed)

**Comment by bradjones1** [comment]
Per the referenced commit above, passing through requests for v1/_ping on a V2 registry isn't going to do you any good since it will still return 400; by a read of the code in docker-py it just looked easier for a V2 registry to send a fake 200 for the V1 endpoint, since docker-py doesn't care which version you're trying to reach, so long as it can get to it while validating the host.
